[package]
name = "toadstool-security-monitoring"
version.workspace = true
edition.workspace = true
description = "ToadStool monitoring component"
license.workspace = true
repository.workspace = true
readme = "README.md"
keywords = ["security", "monitoring", "audit", "compliance"]
categories = ["development-tools::profiling"]

[dependencies]
serde = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
toadstool-common = { path = "../../core/common" }
toadstool-sysmon = { workspace = true }

[dev-dependencies]
tokio = { workspace = true, features = ["rt-multi-thread", "macros", "time"] }

[lints]
workspace = true

