//! Fast Fourier Transform (FFT) Operations
//!
//! **Purpose**: Complex FFT for wave physics and frequency analysis
//!
//! **Evolution**: Adapted from FHE NTT (80% structure reuse!)
//! - NTT: Butterfly in integer modular domain
//! - FFT: Butterfly in complex float domain
//! - SAME algorithm (Cooley-Tukey), DIFFERENT arithmetic
//!
//! **Architecture**:
//! - All math in WGSL shaders (universal GPU portability)
//! - All orchestration in Rust (type safety, zero unsafe)
//!
//! **Deep Debt Compliance**:
//! - ✅ Pure Rust + WGSL (no unsafe code)
//! - ✅ Hardware-agnostic (wgpu backend selection)
//! - ✅ Numerically precise (IEEE 754 float32)
//! - ✅ Production-ready (full error handling)
//!
//! ## Operations
//!
//! - `fft_1d` - 1D Complex FFT (Cooley-Tukey radix-2) ⚠️ **CRITICAL FOR PPPM**
//! - `ifft_1d` - 1D Inverse FFT (conjugate + normalize)
//! - `fft_2d` - 2D FFT via row-column decomposition
//! - `fft_3d` - 3D FFT for PPPM long-range forces
//! - `rfft` - Real-to-complex FFT (optimized)
//!
//! ## Mathematical Background
//!
//! The Discrete Fourier Transform (DFT):
//! ```text
//! X[k] = Σ(n=0 to N-1) x[n] · exp(-2πikn/N)
//! ```
//!
//! FFT accelerates this from O(N²) to O(N log N) via Cooley-Tukey butterfly:
//! ```text
//! Butterfly:
//!   u = a + twiddle * b
//!   v = a - twiddle * b
//! where twiddle = exp(-2πik/N)  ← Generated by complex_exp!
//! ```
//!
//! ## Usage Example
//!
//! ```no_run
//! use barracuda::ops::fft::Fft1D;
//! use barracuda::tensor::Tensor;
//!
//! # async fn example() -> Result<(), Box<dyn std::error::Error>> {
//! let device = Arc::new(WgpuDevice::new().await?);
//!
//! // Create complex signal tensor (interleaved real, imag)
//! let signal = Tensor::from_data(&signal_data, vec![1024, 2], device.clone())?;
//!
//! // Create FFT operation
//! let fft = Fft1D::new(signal, 1024)?;
//!
//! // Execute (returns frequency-domain representation)
//! let spectrum = fft.execute()?;
//! # Ok(())
//! # }
//! ```

pub mod fft_1d;
pub mod ifft_1d;

#[cfg(test)]
mod tests;

pub use fft_1d::Fft1D;
pub use ifft_1d::Ifft1D;
