[package]
name = "toadstool-management-resources"
version.workspace = true
edition.workspace = true
description = "ToadStool resources component"
readme = "README.md"
license.workspace = true
repository = "https://github.com/ecoPrimals/toadstool"
keywords = ["resources", "management", "monitoring", "allocation"]
categories = ["development-tools"]

[dependencies]
