[package]
name = "toadstool-management-resources"
version.workspace = true
edition.workspace = true
description = "ToadStool resources component"
readme = "README.md"
license.workspace = true
repository.workspace = true
keywords = ["resources", "management", "monitoring", "allocation"]
categories = ["development-tools"]

[dependencies]
serde = { workspace = true }
toadstool-common = { path = "../../core/common", default-features = false }
toadstool-sysmon = { workspace = true }

[lints]
workspace = true

