// SPDX-License-Identifier: AGPL-3.0-or-later
//! BAR0 permission management for sovereign GPU compute.
//!
//! Provides udev rule installation for non-root BAR0 access to NVIDIA GPUs.
//! Without this, `Bar0Access` requires root privileges because
//! `/sys/bus/pci/devices/{BDF}/resource0` is root-only by default.
//!
//! # udev Rule
//!
//! The rule matches NVIDIA PCI devices (vendor `0x10de`) and sets
//! `resource0` (BAR0 MMIO) to mode `0660` owned by the `gpu-mmio` group.
//! Users in the `gpu-mmio` group can then open BAR0 without root.
//!
//! # Alternative: setcap
//!
//! For single-binary deployments, `setcap cap_sys_rawio+ep` on the
//! toadStool binary grants BAR0 access without a group. Less persistent
//! than udev (lost on binary rebuild).

use std::fs;
use std::io;
use std::path::Path;

const RULES_FILE: &str = "/etc/udev/rules.d/99-ecoprimals-gpu-bar0.rules";

const UDEV_RULES_CONTENT: &str = r#"# ecoPrimals sovereign GPU BAR0 access
# Auto-generated by nvpmu — enables non-root MMIO for GPU init
#
# Users must be in the 'gpu-mmio' group:
#   sudo groupadd -f gpu-mmio
#   sudo usermod -aG gpu-mmio $USER
#
# NVIDIA vendor 0x10de — resource0 is BAR0 (MMIO registers)
SUBSYSTEM=="pci", ATTR{vendor}=="0x10de", \
  RUN+="/bin/chmod 0660 /sys/bus/pci/devices/%k/resource0"
SUBSYSTEM=="pci", ATTR{vendor}=="0x10de", \
  RUN+="/bin/chgrp gpu-mmio /sys/bus/pci/devices/%k/resource0"
"#;

/// Install udev rules for non-root BAR0 access to NVIDIA GPUs.
///
/// Writes to `/etc/udev/rules.d/99-ecoprimals-gpu-bar0.rules` and
/// triggers a udev reload. Requires root.
///
/// # Errors
///
/// Returns an error if the rules file cannot be written or udev
/// cannot be reloaded (typically means not running as root).
pub fn install_udev_rules() -> io::Result<()> {
    fs::write(RULES_FILE, UDEV_RULES_CONTENT)?;
    tracing::info!("Wrote BAR0 udev rules to {RULES_FILE}");

    let reload = std::process::Command::new("udevadm")
        .args(["control", "--reload-rules"])
        .output()?;
    if !reload.status.success() {
        tracing::warn!("udevadm reload-rules exited with {}", reload.status);
    }

    let trigger = std::process::Command::new("udevadm")
        .arg("trigger")
        .output()?;
    if !trigger.status.success() {
        tracing::warn!("udevadm trigger exited with {}", trigger.status);
    }

    tracing::info!("udev rules reloaded — BAR0 accessible to gpu-mmio group");
    Ok(())
}

/// Check whether BAR0 is accessible for a given PCI BDF without root.
///
/// Returns `true` if `resource0` exists and is readable+writable by
/// the current process.
#[must_use]
pub fn bar0_accessible(bdf: &str) -> bool {
    let path = toadstool_common::sysfs_paths::sysfs_pci_device_file(bdf, "resource0");
    std::fs::OpenOptions::new()
        .read(true)
        .write(true)
        .open(&path)
        .is_ok()
}

/// Check whether the udev rules file is already installed.
#[must_use]
pub fn rules_installed() -> bool {
    Path::new(RULES_FILE).exists()
}

/// Set BAR0 permissions for a specific GPU (immediate, does not persist).
///
/// # Errors
///
/// Returns an error if the chmod fails (likely not root).
pub fn set_bar0_permissions(bdf: &str, mode: u32) -> io::Result<()> {
    let path = toadstool_common::sysfs_paths::sysfs_pci_device_file(bdf, "resource0");
    toadstool_common::platform::set_access(
        path.as_ref(),
        toadstool_common::platform::PlatformAccess::Custom(mode),
    )?;
    tracing::info!("Set {path} to mode {mode:o}");
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn udev_rules_content_is_valid() {
        assert!(UDEV_RULES_CONTENT.contains("0x10de"));
        assert!(UDEV_RULES_CONTENT.contains("resource0"));
        assert!(UDEV_RULES_CONTENT.contains("gpu-mmio"));
    }

    #[test]
    fn rules_file_path_is_valid() {
        assert!(RULES_FILE.starts_with("/etc/udev/rules.d/"));
        assert!(
            std::path::Path::new(RULES_FILE)
                .extension()
                .is_some_and(|ext| ext.eq_ignore_ascii_case("rules"))
        );
    }

    #[test]
    fn bar0_accessible_returns_false_for_nonexistent() {
        assert!(!bar0_accessible("9999:99:99.9"));
    }
}
