//! Core orchestration logic for zero-configuration deployment

use anyhow::Result;
use std::future::Future;
use std::time::{Duration, Instant};
use tracing::info;

use super::types::*;
use super::{ConfigurationExt, DeploymentExt, DiscoveryExt, VerificationExt};

/// Core trait for zero-configuration deployment
pub trait ZeroConfigCore {
    /// Create a new zero-configuration deployment
    fn new() -> Self;

    /// Execute rapid system discovery and configuration
    fn rapid_bootstrap(&mut self) -> impl Future<Output = Result<Duration>> + Send;

    /// Get deployment summary
    fn get_deployment_summary(&self) -> DeploymentSummary;
}

impl Default for ZeroConfigDeployment {
    fn default() -> Self {
        Self::new()
    }
}

impl ZeroConfigCore for ZeroConfigDeployment {
    fn new() -> Self {
        Self {
            system_info: SystemInfo::default(),
            ecosystem_services: EcosystemServices::default(),
            config: AutoGeneratedConfig::default(),
            start_time: Instant::now(),
        }
    }

    async fn rapid_bootstrap(&mut self) -> Result<Duration> {
        let start = Instant::now();

        info!("🚀 Starting zero-configuration deployment");

        // Phase 1: System Discovery (Target: 15 seconds)
        info!("🔍 Phase 1: System Discovery");
        self.discover_system().await?;

        // Phase 2: Ecosystem Discovery (Target: 15 seconds)
        info!("🌐 Phase 2: Ecosystem Discovery");
        self.discover_ecosystem().await?;

        // Phase 3: Configuration Generation (Target: 10 seconds)
        info!("⚙️ Phase 3: Configuration Generation");
        self.generate_configuration().await?;

        // Phase 4: Service Deployment (Target: 15 seconds)
        info!("🚀 Phase 4: Service Deployment");
        self.deploy_services().await?;

        // Phase 5: Health Verification (Target: 5 seconds)
        info!("✅ Phase 5: Health Verification");
        self.verify_health().await?;

        let duration = start.elapsed();
        info!(
            "✅ Zero-configuration deployment completed in {:?}",
            duration
        );

        Ok(duration)
    }

    fn get_deployment_summary(&self) -> DeploymentSummary {
        DeploymentSummary {
            total_time: self.start_time.elapsed(),
            system_info: self.system_info.clone(),
            ecosystem_services: self.ecosystem_services.clone(),
            config: self.config.clone(),
            services_deployed: self.count_deployed_services(),
            health_status: "healthy".to_string(),
        }
    }
}

impl ZeroConfigDeployment {
    /// Count deployed services
    fn count_deployed_services(&self) -> u32 {
        let mut count = 0;

        // Count runtime engines
        count += self.config.runtime.preferred_runtimes.len() as u32;

        // Count ecosystem integrations
        if self.config.network.songbird_enabled {
            count += 1;
        }
        if self.config.security.beardog_enabled {
            count += 1;
        }
        if self.config.storage.nestgate_enabled {
            count += 1;
        }

        // Core services
        count += 2; // orchestrator + monitoring

        count
    }
}

/// CLI command for zero-configuration deployment
pub async fn execute_zero_config_deployment() -> Result<()> {
    use super::ZeroConfigCore;

    let mut deployment = ZeroConfigDeployment::new();

    let duration = deployment.rapid_bootstrap().await?;

    let summary = deployment.get_deployment_summary();

    println!("🎉 Zero-configuration deployment completed successfully!");
    println!("⏱️ Total time: {duration:?}");
    println!(
        "🖥️ System: {} cores, {} GB RAM, {} GB storage",
        summary.system_info.cpu.cores,
        summary.system_info.memory.total_bytes / 1024 / 1024 / 1024,
        summary.system_info.storage.total_bytes / 1024 / 1024 / 1024
    );
    println!("🚀 Services deployed: {}", summary.services_deployed);
    println!("✅ Health status: {}", summary.health_status);

    // Save configuration for future use
    let config_json = serde_json::to_string_pretty(&summary.config)?;
    tokio::fs::write("toadstool-auto-config.json", config_json).await?;

    println!("💾 Configuration saved to toadstool-auto-config.json");

    Ok(())
}
