// SPDX-License-Identifier: AGPL-3.0-or-later
//! Type definitions for zero-configuration deployment

use serde::{Deserialize, Serialize};
use std::time::Instant;

/// Zero-configuration deployment manager
pub struct ZeroConfigDeployment {
    /// System discovery results
    pub system_info: SystemInfo,
    /// Detected ecosystem services
    pub ecosystem_services: EcosystemServices,
    /// Generated configuration
    pub config: AutoGeneratedConfig,
    /// Deployment start time
    pub start_time: Instant,
}

/// System hardware and software information
#[derive(Debug, Clone, Serialize, Deserialize, Default)]
pub struct SystemInfo {
    /// CPU information
    pub cpu: CpuInfo,
    /// Memory information  
    pub memory: MemoryInfo,
    /// Storage information
    pub storage: StorageInfo,
    /// Network information
    pub network: NetworkInfo,
    /// Operating system details
    pub os: OsInfo,
    /// Container runtime availability
    pub container_runtime: ContainerRuntimeInfo,
    /// GPU information
    pub gpu: GpuInfo,
}

/// CPU information
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct CpuInfo {
    /// Number of cores
    pub cores: u32,
    /// CPU architecture
    pub architecture: String,
    /// CPU model
    pub model: String,
    /// CPU frequency in MHz
    pub frequency: u32,
    /// CPU vendor
    pub vendor: String,
}

/// Memory information
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct MemoryInfo {
    /// Total memory in bytes
    pub total_bytes: u64,
    /// Available memory in bytes
    pub available_bytes: u64,
    /// Memory type (DDR4, DDR5, etc.)
    pub memory_type: String,
}

/// Storage information
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct StorageInfo {
    /// Total storage in bytes
    pub total_bytes: u64,
    /// Available storage in bytes
    pub available_bytes: u64,
    /// Storage type (SSD, HDD, NVMe)
    pub storage_type: String,
    /// File system type
    pub filesystem: String,
}

/// Network information
#[derive(Debug, Clone, Serialize, Deserialize, Default)]
pub struct NetworkInfo {
    /// Network interfaces
    pub interfaces: Vec<NetworkInterface>,
    /// External IP address
    pub external_ip: Option<String>,
    /// Local IP addresses
    pub local_ips: Vec<String>,
}

/// Network interface information
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct NetworkInterface {
    /// Interface name
    pub name: String,
    /// IP address
    pub ip: String,
    /// MAC address
    pub mac: String,
    /// Interface speed in Mbps
    pub speed: u32,
}

/// Operating system information
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct OsInfo {
    /// OS name
    pub name: String,
    /// OS version
    pub version: String,
    /// Kernel version
    pub kernel: String,
    /// Architecture
    pub arch: String,
}

/// Container runtime information
#[derive(Debug, Clone, Serialize, Deserialize, Default)]
pub struct ContainerRuntimeInfo {
    /// Docker availability
    pub docker: bool,
    /// Podman availability
    pub podman: bool,
    /// ContainerD availability
    pub containerd: bool,
    /// Runtime version
    pub version: Option<String>,
}

/// GPU information
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct GpuInfo {
    /// GPU count
    pub count: u32,
    /// GPU vendor
    pub vendor: String,
    /// GPU model
    pub model: String,
    /// GPU memory in bytes
    pub memory_bytes: u64,
    /// CUDA availability
    pub cuda: bool,
    /// Legacy field retained for serde compatibility.
    ///
    /// DEPRECATED S198: OpenCL removed — use barraCuda/coralReef via IPC. Always `false` from discovery.
    #[deprecated(note = "DEPRECATED S198: OpenCL removed — use barraCuda/coralReef via IPC")]
    pub opencl: bool,
}

/// Detected ecosystem capability providers.
///
/// Fields use capability-domain names per `CAPABILITY_BASED_DISCOVERY_STANDARD.md`.
/// Serde aliases preserve older config field names where needed.
#[derive(Debug, Clone, Serialize, Deserialize, Default)]
pub struct EcosystemServices {
    /// Coordination / orchestration capability provider
    #[serde(alias = "songbird")]
    pub coordination: Option<ServiceEndpoint>,
    /// Security / crypto capability provider
    #[serde(alias = "beardog")]
    pub security: Option<ServiceEndpoint>,
    /// Storage capability provider
    #[serde(alias = "nestgate")]
    pub storage: Option<ServiceEndpoint>,
    /// AI processing capability provider
    #[serde(alias = "squirrel")]
    pub ai_processing: Option<ServiceEndpoint>,
    /// Other ToadStool instances
    pub toadstool_peers: Vec<ServiceEndpoint>,
}

/// Service endpoint information
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ServiceEndpoint {
    /// Service name
    pub name: String,
    /// Service endpoint URL
    pub endpoint: String,
    /// Service version
    pub version: String,
    /// Service status
    pub status: String,
    /// Authentication required
    pub auth_required: bool,
    /// Discovery timestamp
    #[serde(with = "toadstool_common::system_time_serde")]
    pub discovered_at: std::time::SystemTime,
}

/// Auto-generated configuration
#[derive(Debug, Clone, Serialize, Deserialize, Default)]
pub struct AutoGeneratedConfig {
    /// Biome configuration
    pub biome: BiomeConfig,
    /// Runtime configuration
    pub runtime: RuntimeConfig,
    /// Security configuration
    pub security: SecurityConfig,
    /// Network configuration
    pub network: NetworkConfig,
    /// Storage configuration
    pub storage: StorageConfig,
}

/// Biome configuration
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct BiomeConfig {
    /// Biome name
    pub name: String,
    /// Biome version
    pub version: String,
    /// Biome description
    pub description: String,
    /// Resource allocation
    pub resources: BiomeResources,
}

/// Runtime configuration
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct RuntimeConfig {
    /// Preferred runtime types
    pub preferred_runtimes: Vec<String>,
    /// Container runtime
    pub container_runtime: String,
    /// WASM runtime
    pub wasm_runtime: String,
    /// GPU runtime
    pub gpu_runtime: Option<String>,
}

/// Security configuration
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SecurityConfig {
    /// Security level
    pub level: String,
    /// Isolation level
    pub isolation: String,
    /// Security capability provider integration
    #[serde(alias = "beardog_enabled")]
    pub security_provider_enabled: bool,
    /// Crypto policies
    pub crypto_policies: Vec<String>,
}

/// Network configuration
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct NetworkConfig {
    /// Network mode
    pub mode: String,
    /// Port mappings
    pub port_mappings: Vec<PortMapping>,
    /// DNS servers
    pub dns_servers: Vec<String>,
    /// Coordination capability provider integration
    #[serde(alias = "songbird_enabled")]
    pub coordination_enabled: bool,
}

/// Storage configuration
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct StorageConfig {
    /// Storage backend
    pub backend: String,
    /// Storage capability provider integration
    #[serde(alias = "nestgate_enabled")]
    pub storage_provider_enabled: bool,
    /// Volume configurations
    pub volumes: Vec<VolumeConfig>,
    /// Backup enabled
    pub backup_enabled: bool,
}

/// Port mapping configuration
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PortMapping {
    /// Host port
    pub host_port: u16,
    /// Container port
    pub container_port: u16,
    /// Protocol
    pub protocol: String,
}

/// Volume configuration
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct VolumeConfig {
    /// Volume name
    pub name: String,
    /// Volume size
    pub size: String,
    /// Mount point
    pub mount_point: String,
    /// Read-only flag
    pub read_only: bool,
}

/// Biome resources
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct BiomeResources {
    /// CPU allocation
    pub cpu_limit: f64,
    /// Memory allocation
    pub memory_limit: String,
    /// Storage allocation
    pub storage_limit: String,
    /// GPU allocation
    pub gpu_limit: Option<u32>,
}

/// Deployment summary information
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct DeploymentSummary {
    /// Total deployment time
    pub total_time: std::time::Duration,
    /// System information
    pub system_info: SystemInfo,
    /// Ecosystem services
    pub ecosystem_services: EcosystemServices,
    /// Generated configuration
    pub config: AutoGeneratedConfig,
    /// Number of services deployed
    pub services_deployed: u32,
    /// Overall health status
    pub health_status: String,
}

// Default implementations

impl Default for CpuInfo {
    fn default() -> Self {
        Self {
            cores: 1,
            architecture: String::from("unknown"),
            model: String::from("unknown"),
            frequency: 0,
            vendor: String::from("unknown"),
        }
    }
}

impl Default for MemoryInfo {
    fn default() -> Self {
        Self {
            total_bytes: 0,
            available_bytes: 0,
            memory_type: String::from("unknown"),
        }
    }
}

impl Default for StorageInfo {
    fn default() -> Self {
        Self {
            total_bytes: 0,
            available_bytes: 0,
            storage_type: String::from("unknown"),
            filesystem: String::from("unknown"),
        }
    }
}

impl Default for OsInfo {
    fn default() -> Self {
        Self {
            name: String::from("unknown"),
            version: String::from("unknown"),
            kernel: String::from("unknown"),
            arch: String::from("unknown"),
        }
    }
}

impl Default for GpuInfo {
    #[expect(deprecated, reason = "GpuInfo fields during S198 migration")]
    fn default() -> Self {
        Self {
            count: 0,
            vendor: String::from("none"),
            model: String::from("none"),
            memory_bytes: 0,
            cuda: false,
            opencl: false,
        }
    }
}

impl Default for BiomeConfig {
    fn default() -> Self {
        Self {
            name: String::from("default"),
            version: String::from("1.0.0"),
            description: String::from("Auto-generated biome configuration"),
            resources: BiomeResources::default(),
        }
    }
}

impl Default for RuntimeConfig {
    fn default() -> Self {
        Self {
            preferred_runtimes: vec![String::from("native"), String::from("wasm")],
            container_runtime: String::from("docker"),
            wasm_runtime: String::from("wasmtime"),
            gpu_runtime: None,
        }
    }
}

impl Default for SecurityConfig {
    fn default() -> Self {
        Self {
            level: String::from("standard"),
            isolation: String::from("process"),
            security_provider_enabled: false,
            crypto_policies: vec![String::from("tls1.3"), String::from("aes256")],
        }
    }
}

impl Default for NetworkConfig {
    fn default() -> Self {
        Self {
            mode: String::from("bridge"),
            port_mappings: Vec::new(),
            // Empty: DNS servers are provided by the environment or operator config.
            dns_servers: Vec::new(),
            coordination_enabled: false,
        }
    }
}

impl Default for StorageConfig {
    fn default() -> Self {
        Self {
            backend: String::from("local"),
            storage_provider_enabled: false,
            volumes: Vec::new(),
            backup_enabled: false,
        }
    }
}

impl Default for BiomeResources {
    fn default() -> Self {
        Self {
            cpu_limit: 1.0,
            memory_limit: String::from("512M"),
            storage_limit: String::from("10G"),
            gpu_limit: None,
        }
    }
}
