#!/usr/bin/env bash
#
# ToadStool Runtime Selection Guide Demo
# Interactive guide to choosing the right runtime for your workload
#

set -e

# Color codes
GREEN='\033[0;32m'
CYAN='\033[0;36m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
MAGENTA='\033[0;35m'
RED='\033[0;31m'
NC='\033[0m' # No Color

echo "════════════════════════════════════════════════════════"
echo "🍄 ToadStool Runtime Selection Guide"
echo "════════════════════════════════════════════════════════"
echo ""
echo "This interactive demo helps you choose the right runtime"
echo "for your specific workload!"
echo ""

# Decision tree
echo "Step 1: Quick decision tree..."
echo ""
echo "   ${CYAN}Answer these questions:${NC}"
echo ""
echo "   ❓ Is your code from an untrusted source?"
echo "      └─ ${GREEN}YES${NC} → WASM (sandboxed security)"
echo "      └─ NO → Continue..."
echo ""
echo "   ❓ Does your workload involve ML/AI?"
echo "      └─ ${GREEN}YES${NC} → Python (+ GPU if available)"
echo "      └─ NO → Continue..."
echo ""
echo "   ❓ Do you need maximum performance?"
echo "      └─ ${GREEN}YES${NC} → Native (raw speed)"
echo "      └─ NO → Continue..."
echo ""
echo "   ❓ Must it run cross-platform?"
echo "      └─ ${GREEN}YES${NC} → WASM (portable)"
echo "      └─ NO → Native (platform-specific OK)"
echo ""

# Common scenarios
echo "Step 2: Common scenarios..."
echo ""
echo "   ${BLUE}Scenario A: User-Submitted Plugin${NC}"
echo "   • Source: Untrusted"
echo "   • Security: Critical"
echo "   • Performance: Moderate OK"
echo "   ${GREEN}→ Recommendation: WASM${NC}"
echo ""
echo "   ${BLUE}Scenario B: ML Model Inference${NC}"
echo "   • Libraries: TensorFlow, PyTorch"
echo "   • Ecosystem: Python-centric"
echo "   • Development speed: Important"
echo "   ${GREEN}→ Recommendation: Python${NC}"
echo ""
echo "   ${BLUE}Scenario C: High-Frequency Trading${NC}"
echo "   • Latency: Every microsecond counts"
echo "   • Performance: Critical"
echo "   • Trust: Internal code"
echo "   ${GREEN}→ Recommendation: Native${NC}"
echo ""
echo "   ${BLUE}Scenario D: Edge IoT Device${NC}"
echo "   • Memory: Limited (64MB)"
echo "   • Portability: Multiple platforms"
echo "   • Updates: Over-the-air"
echo "   ${GREEN}→ Recommendation: WASM${NC}"
echo ""

# Detailed comparison
echo "Step 3: Detailed runtime comparison..."
echo ""
echo "   ┌────────────────┬─────────┬────────┬─────────┐"
echo "   │ Characteristic │ Native  │  WASM  │ Python  │"
echo "   ├────────────────┼─────────┼────────┼─────────┤"
echo "   │ Speed          │ ⭐⭐⭐⭐⭐  │ ⭐⭐⭐⭐   │ ⭐⭐⭐     │"
echo "   │ Security       │ ⭐⭐      │ ⭐⭐⭐⭐⭐  │ ⭐⭐⭐     │"
echo "   │ Memory         │ ⭐⭐⭐     │ ⭐⭐⭐⭐⭐  │ ⭐⭐      │"
echo "   │ Startup        │ ⭐⭐⭐⭐⭐  │ ⭐⭐⭐⭐   │ ⭐⭐      │"
echo "   │ Portability    │ ⭐       │ ⭐⭐⭐⭐⭐  │ ⭐⭐⭐⭐    │"
echo "   │ ML Ecosystem   │ ⭐⭐      │ ⭐⭐     │ ⭐⭐⭐⭐⭐   │"
echo "   │ Ease of Dev    │ ⭐⭐⭐     │ ⭐⭐⭐    │ ⭐⭐⭐⭐⭐   │"
echo "   │ Binary Size    │ ⭐⭐⭐     │ ⭐⭐⭐⭐⭐  │ ⭐⭐      │"
echo "   └────────────────┴─────────┴────────┴─────────┘"
echo ""

# Use case matrix
echo "Step 4: Use case → Runtime matrix..."
echo ""
echo "   ┌──────────────────────────┬────────────────────┐"
echo "   │       Use Case           │   Best Runtime     │"
echo "   ├──────────────────────────┼────────────────────┤"
echo "   │ ML Training              │ Python + GPU       │"
echo "   │ ML Inference (batch)     │ Python + GPU       │"
echo "   │ ML Inference (realtime)  │ Native + GPU       │"
echo "   │ User plugins             │ WASM               │"
echo "   │ Data validation          │ WASM               │"
echo "   │ File I/O                 │ Native             │"
echo "   │ Network services         │ Native             │"
echo "   │ Data processing          │ Python             │"
echo "   │ ETL pipelines            │ Python             │"
echo "   │ Image processing         │ Native or Python   │"
echo "   │ Real-time systems        │ Native             │"
echo "   │ Edge computing           │ WASM               │"
echo "   │ Serverless functions     │ WASM               │"
echo "   │ Game mods                │ WASM               │"
echo "   │ Scientific computing     │ Python             │"
echo "   └──────────────────────────┴────────────────────┘"
echo ""

# Red flags
echo "Step 5: Red flags (anti-patterns)..."
echo ""
echo "   ${RED}❌ DON'T: Use Native for untrusted code${NC}"
echo "   → Security risk! Use WASM instead."
echo ""
echo "   ${RED}❌ DON'T: Use Python for real-time systems${NC}"
echo "   → Too slow! Use Native instead."
echo ""
echo "   ${RED}❌ DON'T: Use WASM for heavy I/O${NC}"
echo "   → Limited APIs! Use Native instead."
echo ""
echo "   ${RED}❌ DON'T: Use Native for cross-platform${NC}"
echo "   → Requires multiple binaries! Use WASM."
echo ""
echo "   ${RED}❌ DON'T: Use WASM for ML (yet)${NC}"
echo "   → Limited ecosystem! Use Python."
echo ""

# Best practices
echo "Step 6: Best practices..."
echo ""
echo "   ${GREEN}✅ DO: Profile before optimizing${NC}"
echo "   Measure actual performance, don't assume!"
echo ""
echo "   ${GREEN}✅ DO: Start with Python for prototypes${NC}"
echo "   Faster development, migrate hot paths later."
echo ""
echo "   ${GREEN}✅ DO: Use WASM for user content${NC}"
echo "   Plugins, mods, extensions → always WASM."
echo ""
echo "   ${GREEN}✅ DO: Mix runtimes in pipelines${NC}"
echo "   Use the right tool for each step!"
echo ""
echo "   ${GREEN}✅ DO: Consider maintenance${NC}"
echo "   Python often wins on total cost of ownership."
echo ""

# Decision flowchart
echo "Step 7: Complete decision flowchart..."
echo ""
echo "   Start"
echo "    │"
echo "    ↓"
echo "   Is code untrusted?"
echo "   ├─ YES → ${CYAN}WASM${NC} (Security first!)"
echo "   └─ NO ↓"
echo "    │"
echo "   Is it ML/AI workload?"
echo "   ├─ YES → ${YELLOW}Python${NC} (+ GPU if available)"
echo "   └─ NO ↓"
echo "    │"
echo "   Is latency critical (<1ms)?"
echo "   ├─ YES → ${BLUE}Native${NC} (Maximum performance)"
echo "   └─ NO ↓"
echo "    │"
echo "   Heavy I/O operations?"
echo "   ├─ YES → ${BLUE}Native${NC} (Fast I/O)"
echo "   └─ NO ↓"
echo "    │"
echo "   Cross-platform required?"
echo "   ├─ YES → ${CYAN}WASM${NC} (Write once, run anywhere)"
echo "   └─ NO ↓"
echo "    │"
echo "   Large Python ecosystem needed?"
echo "   ├─ YES → ${YELLOW}Python${NC} (Batteries included)"
echo "   └─ NO → ${BLUE}Native${NC} (Default choice)"
echo ""

# Performance tiers
echo "Step 8: Performance tiers..."
echo ""
echo "   ${BLUE}Tier 1: Maximum Performance${NC}"
echo "   • Use Native"
echo "   • Examples: HFT, game engines, real-time"
echo "   • Trade-off: Platform-specific, less secure"
echo ""
echo "   ${CYAN}Tier 2: Balanced${NC}"
echo "   • Use WASM"
echo "   • Examples: Plugins, edge computing, serverless"
echo "   • Trade-off: 10-20% overhead vs Native"
echo ""
echo "   ${YELLOW}Tier 3: Developer Productivity${NC}"
echo "   • Use Python"
echo "   • Examples: ML, data science, prototyping"
echo "   • Trade-off: 2-5x slower, more memory"
echo ""

# Final recommendations
echo "Step 9: Final recommendations..."
echo ""
echo "   ${MAGENTA}For most applications:${NC}"
echo "   1. Start with Python (fast development)"
echo "   2. Profile and identify bottlenecks"
echo "   3. Move hot paths to Native/WASM"
echo "   4. Keep Python for ML/data tasks"
echo ""
echo "   ${MAGENTA}For security-critical:${NC}"
echo "   1. Always use WASM for untrusted code"
echo "   2. Native only for trusted, internal code"
echo "   3. Never run user code in Native"
echo ""
echo "   ${MAGENTA}For performance-critical:${NC}"
echo "   1. Profile first! (Don't guess)"
echo "   2. Native for proven bottlenecks"
echo "   3. WASM if cross-platform needed"
echo "   4. Consider GPU for parallelizable tasks"
echo ""

# Summary
echo "════════════════════════════════════════════════════════"
echo -e "${GREEN}✅ Runtime Selection Guide Complete!${NC}"
echo "════════════════════════════════════════════════════════"
echo ""
echo "🎓 What you learned:"
echo "   • Decision tree for runtime selection"
echo "   • Common scenarios and patterns"
echo "   • Anti-patterns to avoid"
echo "   • Best practices for production"
echo ""
echo "💡 Key Takeaway:"
echo "   ${MAGENTA}Right tool for the right job!${NC}"
echo "   Security → WASM"
echo "   ML/AI → Python"
echo "   Performance → Native"
echo ""
echo "🏆 Level 1 Complete!"
echo "   You've mastered multi-runtime workflows!"
echo ""
echo "➡️  What's Next?"
echo "   • Level 2: ../03-resource-management/"
echo "     (Learn CPU/memory limits and fair scheduling)"
echo "   • Level 4: ../05-gpu-compute/"
echo "     (GPU acceleration demos)"
echo "   • Level 5: ../06-production-patterns/"
echo "     (Real-world production patterns)"
echo ""
echo "🍄 You're a runtime expert now!"
echo ""

