// SPDX-License-Identifier: AGPL-3.0-or-later
//! Permission management

use crate::error::{Result, SetupError};
use std::fs;
use std::os::unix::fs::PermissionsExt;
use std::path::Path;

const UDEV_RULES_CONTENT: &str = r#"# Akida PCIe device permissions
# Auto-generated by akida-setup
KERNEL=="akida[0-9]*", MODE="0666"
KERNEL=="akd1500_[0-9]*", MODE="0666"

# PCIe resource access for userspace drivers
SUBSYSTEM=="pci", ATTR{vendor}=="0x1e7c", ATTR{device}=="0xbca1", \
  RUN+="/bin/chmod 666 /sys/bus/pci/devices/%k/resource*", \
  RUN+="/bin/chmod 666 /sys/bus/pci/devices/%k/enable"
"#;

/// Install udev rules for persistent permissions
pub fn setup_udev_rules() -> Result<()> {
    let rules_path = "/etc/udev/rules.d/99-akida-pcie.rules";

    // Write rules file
    fs::write(rules_path, UDEV_RULES_CONTENT)
        .map_err(|e| SetupError::Setup(format!("Failed to write udev rules: {e}")))?;

    tracing::info!("Wrote udev rules to {}", rules_path);

    // Reload udev
    std::process::Command::new("udevadm")
        .args(["control", "--reload-rules"])
        .output()
        .map_err(|e| SetupError::Setup(format!("Failed to reload udev rules: {e}")))?;

    // Trigger udev
    std::process::Command::new("udevadm")
        .arg("trigger")
        .output()
        .map_err(|e| SetupError::Setup(format!("Failed to trigger udev: {e}")))?;

    Ok(())
}

/// Set permissions on device nodes
pub fn setup_device_permissions() -> Result<()> {
    let patterns = vec!["/dev/akida*"];

    for pattern in patterns {
        // Use glob to find matching devices
        for entry in glob::glob(pattern)? {
            let path = entry?;
            set_file_permissions(&path, 0o666)?;
            tracing::debug!("Set permissions for {}", path.display());
        }
    }

    Ok(())
}

/// Set permissions on `PCIe` resource files
pub fn setup_pcie_permissions(pcie_address: &str) -> Result<()> {
    let device_path = format!("/sys/bus/pci/devices/{pcie_address}");

    // Set permissions on resource files
    for entry in fs::read_dir(&device_path)? {
        let entry = entry?;
        let path = entry.path();

        if let Some(name) = path.file_name().and_then(|n| n.to_str()) {
            if name.starts_with("resource") || name == "enable" || name == "config" {
                set_file_permissions(&path, 0o666)?;
            }
        }
    }

    Ok(())
}

/// Set file permissions
fn set_file_permissions(path: &Path, mode: u32) -> Result<()> {
    let metadata = fs::metadata(path)?;
    let mut permissions = metadata.permissions();
    permissions.set_mode(mode);
    fs::set_permissions(path, permissions)?;
    Ok(())
}

/// List device nodes
pub fn list_device_nodes() -> Result<Vec<String>> {
    let mut nodes = Vec::new();

    for path in (glob::glob("/dev/akida*")?).flatten() {
        nodes.push(path.display().to_string());
    }

    Ok(nodes)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_list_device_nodes() {
        let result = list_device_nodes();
        assert!(result.is_ok());
        let nodes = result.unwrap();
        assert!(nodes.iter().all(|n| n.contains("akida")));
    }
}
