// SPDX-License-Identifier: AGPL-3.0-or-later
//! Permission management

use crate::error::{Result, SetupError};

#[cfg(target_os = "linux")]
use std::fs;
#[cfg(target_os = "linux")]
use std::path::Path;

#[cfg(target_os = "linux")]
const UDEV_RULES_CONTENT: &str = r#"# Akida PCIe device permissions
# Auto-generated by akida-setup
KERNEL=="akida[0-9]*", MODE="0666"
KERNEL=="akd1500_[0-9]*", MODE="0666"

# PCIe resource access for userspace drivers
SUBSYSTEM=="pci", ATTR{vendor}=="0x1e7c", ATTR{device}=="0xbca1", \
  RUN+="/bin/chmod 666 /sys/bus/pci/devices/%k/resource*", \
  RUN+="/bin/chmod 666 /sys/bus/pci/devices/%k/enable"
"#;

/// Install udev rules for persistent permissions
#[cfg(target_os = "linux")]
pub fn setup_udev_rules() -> Result<()> {
    let rules_path = "/etc/udev/rules.d/99-akida-pcie.rules";

    // Write rules file
    fs::write(rules_path, UDEV_RULES_CONTENT)
        .map_err(|e| SetupError::Setup(format!("Failed to write udev rules: {e}")))?;

    tracing::info!("Wrote udev rules to {}", rules_path);

    // Reload udev
    std::process::Command::new("udevadm")
        .args(["control", "--reload-rules"])
        .output()
        .map_err(|e| SetupError::Setup(format!("Failed to reload udev rules: {e}")))?;

    // Trigger udev
    std::process::Command::new("udevadm")
        .arg("trigger")
        .output()
        .map_err(|e| SetupError::Setup(format!("Failed to trigger udev: {e}")))?;

    Ok(())
}

/// Install udev rules for persistent permissions
#[cfg(not(target_os = "linux"))]
pub fn setup_udev_rules() -> Result<()> {
    Err(SetupError::Setup(
        "udev rules are only supported on Unix platforms".to_string(),
    ))
}

/// Set permissions on device nodes
#[cfg(target_os = "linux")]
pub fn setup_device_permissions() -> Result<()> {
    let patterns = vec!["/dev/akida*"];

    for pattern in patterns {
        // Use glob to find matching devices
        for entry in glob::glob(pattern)? {
            let path = entry?;
            set_file_permissions(&path, 0o666)?;
            tracing::debug!("Set permissions for {}", path.display());
        }
    }

    Ok(())
}

/// Set permissions on device nodes
#[cfg(not(target_os = "linux"))]
pub fn setup_device_permissions() -> Result<()> {
    Err(SetupError::Setup(
        "Akida device permissions are only supported on Unix platforms".to_string(),
    ))
}

/// Set permissions on `PCIe` resource files
#[cfg(target_os = "linux")]
pub fn setup_pcie_permissions(pcie_address: &str) -> Result<()> {
    let device_path = format!("/sys/bus/pci/devices/{pcie_address}");

    // Set permissions on resource files
    for entry in fs::read_dir(&device_path)? {
        let entry = entry?;
        let path = entry.path();

        if let Some(name) = path.file_name().and_then(|n| n.to_str())
            && (name.starts_with("resource") || name == "enable" || name == "config")
        {
            set_file_permissions(&path, 0o666)?;
        }
    }

    Ok(())
}

/// Set permissions on `PCIe` resource files
#[cfg(not(target_os = "linux"))]
pub fn setup_pcie_permissions(_pcie_address: &str) -> Result<()> {
    Err(SetupError::Setup(
        "PCIe sysfs permissions are only supported on Unix platforms".to_string(),
    ))
}

/// Set file permissions
#[cfg(target_os = "linux")]
fn set_file_permissions(path: &Path, mode: u32) -> Result<()> {
    toadstool_common::platform::set_access(
        path,
        toadstool_common::platform::PlatformAccess::Custom(mode),
    )?;
    Ok(())
}

/// List device nodes
#[cfg(target_os = "linux")]
pub fn list_device_nodes() -> Result<Vec<String>> {
    let mut nodes = Vec::new();

    for path in (glob::glob("/dev/akida*")?).flatten() {
        nodes.push(path.display().to_string());
    }

    Ok(nodes)
}

/// List device nodes
#[cfg(not(target_os = "linux"))]
pub fn list_device_nodes() -> Result<Vec<String>> {
    Ok(Vec::new())
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_list_device_nodes() {
        let result = list_device_nodes();
        assert!(result.is_ok());
        let nodes = result.unwrap();
        #[cfg(target_os = "linux")]
        assert!(nodes.iter().all(|n| n.contains("akida")));
        #[cfg(not(target_os = "linux"))]
        assert!(nodes.is_empty());
    }
}
