//! Generic batched ODE RK4 solver for barracuda.
//!
//! Replaces the 5 domain-specific ODE shaders from wetSpring (phage_defense,
//! bistable, multi_signal, cooperation, capacitor) with a single generic
//! infrastructure. New ODE systems are added by implementing [`OdeSystem`]
//! without writing a new WGSL shader each time.
//!
//! # Example
//!
//! ```ignore
//! use barracuda::numerical::ode_generic::{BatchedOdeRK4, OdeSystem};
//!
//! struct ExponentialDecay;
//! impl OdeSystem for ExponentialDecay {
//!     const N_VARS: usize = 1;
//!     const N_PARAMS: usize = 1;
//!
//!     fn system_name() -> &'static str { "exponential_decay" }
//!
//!     fn wgsl_derivative() -> &'static str {
//!         r#"
//! fn deriv(state: array<f64, 1>, params: array<f64, 1>, t: f64) -> array<f64, 1> {
//!     let k = params[0];
//!     var dy: array<f64, 1>;
//!     dy[0] = -k * state[0];
//!     return dy;
//! }
//! "#
//!     }
//! }
//!
//! let initial = vec![1.0, 1.0];  // 2 batches, 1 var each
//! let params = vec![1.0, 2.0];   // k=1 and k=2
//! let finals = BatchedOdeRK4::<ExponentialDecay>::integrate_cpu(
//!     &initial, &params, 0.01, 100, 2
//! );
//! ```

use std::marker::PhantomData;

use crate::error::{BarracudaError, Result};

/// WGSL RK4 integration kernel template.
///
/// Placeholders: `{{N_VARS}}`, `{{N_PARAMS}}`, `{{DERIVATIVE_FN}}`, `{{UNROLLED_*}}`
/// Loops are unrolled because WGSL requires constant indexing for array parameters.
fn wgsl_rk4_template(n_vars: usize, n_params: usize, derivative_fn: &str) -> String {
    let unroll_state2_from = |k: &str, coeff: &str| {
        (0..n_vars)
            .map(|i| format!("    state2[{i}u] = state[{i}u] + {coeff} * {k}[{i}u];"))
            .collect::<Vec<_>>()
            .join("\n")
    };
    let unroll_yn = || {
        (0..n_vars)
            .map(|i| {
                format!(
                    "    yn[{i}u] = state[{i}u] + h * sixth * (k1[{i}u] + two * k2[{i}u] + two * k3[{i}u] + k4[{i}u]);"
                )
            })
            .collect::<Vec<_>>()
            .join("\n")
    };
    let unroll_read_state = || {
        (0..n_vars)
            .map(|i| format!("    state[{i}u] = initial_states[s_base + {i}u];"))
            .collect::<Vec<_>>()
            .join("\n")
    };
    let unroll_read_params = || {
        (0..n_params)
            .map(|i| format!("    params[{i}u] = batch_params[p_base + {i}u];"))
            .collect::<Vec<_>>()
            .join("\n")
    };
    let unroll_clamp = || {
        (0..n_vars)
            .map(|i| format!("        state[{i}u] = fclamp(yn[{i}u], cmin, cmax);"))
            .collect::<Vec<_>>()
            .join("\n")
    };
    let unroll_write = || {
        (0..n_vars)
            .map(|i| format!("    output_states[s_base + {i}u] = state[{i}u];"))
            .collect::<Vec<_>>()
            .join("\n")
    };

    format!(
        r#"// Generic batched ODE RK4 — generated by BatchedOdeRK4<S>
// f64 enabled by compile_shader_f64() preamble injection

const N_VARS:   u32 = {}u;
const N_PARAMS: u32 = {}u;

struct OdeConfig {{
    n_batches:      u32,
    n_steps:        u32,
    _pad0:          u32,
    _pad1:          u32,
    h:              f64,
    t0:             f64,
    clamp_max:      f64,
    clamp_min:      f64,
}}

@group(0) @binding(0) var<uniform>             config:         OdeConfig;
@group(0) @binding(1) var<storage, read>       initial_states: array<f64>;
@group(0) @binding(2) var<storage, read>       batch_params:   array<f64>;
@group(0) @binding(3) var<storage, read_write> output_states:  array<f64>;

fn fclamp(x: f64, lo: f64, hi: f64) -> f64 {{
    if (x < lo) {{ return lo; }}
    if (x > hi) {{ return hi; }}
    return x;
}}

{}

fn rk4_step(state: array<f64, {}>, params: array<f64, {}>, t: f64, h: f64) -> array<f64, {}> {{
    let z = h - h;
    let half = z + 0.5;
    let two = z + 2.0;
    let h2 = h * half;

    let k1 = deriv(state, params, t);
    var state2: array<f64, {}>;
{}
    let k2 = deriv(state2, params, t + h2);

{}
    let k3 = deriv(state2, params, t + h2);

{}
    let k4 = deriv(state2, params, t + h);

    var yn: array<f64, {}>;
    let sixth = (z + 1.0) / (z + 6.0);
{}
    return yn;
}}

@compute @workgroup_size(64)
fn main(@builtin(global_invocation_id) global_id: vec3<u32>) {{
    let b = global_id.x;
    if (b >= config.n_batches) {{ return; }}

    let s_base = b * N_VARS;
    let p_base = b * N_PARAMS;

    var state: array<f64, {}>;
{}
    var params: array<f64, {}>;
{}
    let cmax = config.clamp_max;
    let cmin = config.clamp_min;
    let h = config.h;
    var t = config.t0;

    for (var step = 0u; step < config.n_steps; step = step + 1u) {{
        let yn = rk4_step(state, params, t, h);
{}
        t = t + h;
    }}

{}
}}
"#,
        n_vars,
        n_params,
        derivative_fn,
        n_vars,
        n_params,
        n_vars,
        n_vars,
        unroll_state2_from("k1", "h2"),
        unroll_state2_from("k2", "h2"),
        unroll_state2_from("k3", "h"),
        n_vars,
        unroll_yn(),
        n_vars,
        unroll_read_state(),
        n_params,
        unroll_read_params(),
        unroll_clamp(),
        unroll_write(),
    )
}

/// Universal precision RK4 template using `Scalar`/`op_*` abstractions.
///
/// Generates WGSL that works with any precision preamble (f32, f64, df64, f16).
/// The derivative function must use `Scalar` instead of `f64`.
/// The appropriate precision preamble is prepended by the device's
/// `compile_op_shader()` method.
fn wgsl_rk4_template_universal(n_vars: usize, n_params: usize, derivative_fn: &str) -> String {
    let unroll_state2_from = |k: &str, coeff: &str| {
        (0..n_vars)
            .map(
                |i| format!("    state2[{i}u] = op_add(state[{i}u], op_mul({coeff}, {k}[{i}u]));",),
            )
            .collect::<Vec<_>>()
            .join("\n")
    };
    let unroll_yn = || {
        (0..n_vars)
            .map(|i| {
                format!(
                    "    yn[{i}u] = op_add(state[{i}u], op_mul(h, op_mul(sixth, op_add(op_add(k1[{i}u], op_mul(two, k2[{i}u])), op_add(op_mul(two, k3[{i}u]), k4[{i}u])))));"
                )
            })
            .collect::<Vec<_>>()
            .join("\n")
    };
    let unroll_read_state = || {
        (0..n_vars)
            .map(|i| format!("    state[{i}u] = initial_states[s_base + {i}u];"))
            .collect::<Vec<_>>()
            .join("\n")
    };
    let unroll_read_params = || {
        (0..n_params)
            .map(|i| format!("    params[{i}u] = batch_params[p_base + {i}u];"))
            .collect::<Vec<_>>()
            .join("\n")
    };
    let unroll_clamp = || {
        (0..n_vars)
            .map(|i| format!("        state[{i}u] = op_max(cmin, op_min(cmax, yn[{i}u]));"))
            .collect::<Vec<_>>()
            .join("\n")
    };
    let unroll_write = || {
        (0..n_vars)
            .map(|i| format!("    output_states[s_base + {i}u] = state[{i}u];"))
            .collect::<Vec<_>>()
            .join("\n")
    };

    format!(
        r#"// Generic batched ODE RK4 — universal precision (Scalar/op_*)
// Precision preamble injected by compile_op_shader()

const N_VARS:   u32 = {n_vars}u;
const N_PARAMS: u32 = {n_params}u;

struct OdeConfig {{
    n_batches:      u32,
    n_steps:        u32,
    _pad0:          u32,
    _pad1:          u32,
    h:              Scalar,
    t0:             Scalar,
    clamp_max:      Scalar,
    clamp_min:      Scalar,
}}

@group(0) @binding(0) var<uniform>             config:         OdeConfig;
@group(0) @binding(1) var<storage, read>       initial_states: array<Scalar>;
@group(0) @binding(2) var<storage, read>       batch_params:   array<Scalar>;
@group(0) @binding(3) var<storage, read_write> output_states:  array<Scalar>;

{derivative_fn}

fn rk4_step(state: array<Scalar, {n_vars}>, params: array<Scalar, {n_params}>, t: Scalar, h: Scalar) -> array<Scalar, {n_vars}> {{
    let half = op_from_f32(0.5);
    let two  = op_from_f32(2.0);
    let h2   = op_mul(h, half);

    let k1 = deriv(state, params, t);
    var state2: array<Scalar, {n_vars}>;
{unroll_k1}
    let k2 = deriv(state2, params, op_add(t, h2));

{unroll_k2}
    let k3 = deriv(state2, params, op_add(t, h2));

{unroll_k3}
    let k4 = deriv(state2, params, op_add(t, h));

    var yn: array<Scalar, {n_vars}>;
    let sixth = op_div(op_one(), op_from_f32(6.0));
{unroll_yn}
    return yn;
}}

@compute @workgroup_size(64)
fn main(@builtin(global_invocation_id) global_id: vec3<u32>) {{
    let b = global_id.x;
    if (b >= config.n_batches) {{ return; }}

    let s_base = b * N_VARS;
    let p_base = b * N_PARAMS;

    var state: array<Scalar, {n_vars}>;
{read_state}
    var params: array<Scalar, {n_params}>;
{read_params}
    let cmax = config.clamp_max;
    let cmin = config.clamp_min;
    let h = config.h;
    var t = config.t0;

    for (var step = 0u; step < config.n_steps; step = step + 1u) {{
        let yn = rk4_step(state, params, t, h);
{clamp}
        t = op_add(t, h);
    }}

{write}
}}
"#,
        unroll_k1 = unroll_state2_from("k1", "h2"),
        unroll_k2 = unroll_state2_from("k2", "h2"),
        unroll_k3 = unroll_state2_from("k3", "h"),
        unroll_yn = unroll_yn(),
        read_state = unroll_read_state(),
        read_params = unroll_read_params(),
        clamp = unroll_clamp(),
        write = unroll_write(),
    )
}

/// Trait for ODE systems that can be integrated by the generic batched RK4 solver.
///
/// Implement this trait to add new ODE systems without writing a new WGSL shader.
/// The derivative function must have the signature:
/// `fn deriv(state: array<f64, N_VARS>, params: array<f64, N_PARAMS>, t: f64) -> array<f64, N_VARS>`
pub trait OdeSystem {
    /// Number of state variables.
    const N_VARS: usize;
    /// Number of parameters per batch.
    const N_PARAMS: usize;

    /// Name used for WGSL function generation and diagnostics.
    fn system_name() -> &'static str;

    /// WGSL source for the derivative function (f64).
    ///
    /// Must define: `fn deriv(state: array<f64, N_VARS>, params: array<f64, N_PARAMS>, t: f64) -> array<f64, N_VARS>`
    fn wgsl_derivative() -> &'static str;

    /// WGSL source for the derivative function using universal precision (`Scalar`/`op_*`).
    ///
    /// Must define: `fn deriv(state: array<Scalar, N_VARS>, params: array<Scalar, N_PARAMS>, t: Scalar) -> array<Scalar, N_VARS>`
    ///
    /// Default: `None` (falls back to f64 variant). Implement this when evolving
    /// ODE systems to universal precision.
    fn wgsl_derivative_universal() -> Option<&'static str> {
        None
    }

    /// CPU implementation of the derivative for testing and small batches.
    ///
    /// Returns dy/dt given time, state, and params. The params slice has length N_PARAMS.
    fn cpu_derivative(_t: f64, state: &[f64], params: &[f64]) -> Vec<f64>;
}

/// Batched 4th-order Runge-Kutta ODE integrator.
///
/// Integrates multiple parameter sets in parallel. Each batch has its own
/// initial state and parameter vector. Uses fixed-step RK4.
#[must_use]
pub struct BatchedOdeRK4<S: OdeSystem> {
    _marker: PhantomData<S>,
}

impl<S: OdeSystem> BatchedOdeRK4<S> {
    /// Generate complete f64 WGSL shader source by combining the RK4 template with the system's derivative.
    #[must_use]
    pub fn generate_shader() -> String {
        wgsl_rk4_template(S::N_VARS, S::N_PARAMS, S::wgsl_derivative())
    }

    /// Generate universal-precision WGSL shader using `Scalar`/`op_*`.
    ///
    /// Returns `Some(shader)` if the system provides a universal derivative,
    /// `None` otherwise. Compile with `compile_op_shader()` and a
    /// [`Precision`](crate::shaders::precision::Precision) to select precision.
    #[must_use]
    pub fn generate_shader_universal() -> Option<String> {
        S::wgsl_derivative_universal()
            .map(|deriv| wgsl_rk4_template_universal(S::N_VARS, S::N_PARAMS, deriv))
    }

    /// Run batched RK4 integration on CPU (for testing / small batches).
    ///
    /// # Arguments
    /// * `initial_states` — flat `[batch_size × N_VARS]` f64 slice (row-major)
    /// * `params` — flat `[batch_size × N_PARAMS]` f64 slice (row-major)
    /// * `dt` — fixed step size
    /// * `n_steps` — number of RK4 steps
    /// * `batch_size` — number of independent trajectories
    ///
    /// # Returns
    /// Flat `[batch_size × N_VARS]` f64 `Vec` with the final state for each batch.
    pub fn integrate_cpu(
        initial_states: &[f64],
        params: &[f64],
        dt: f64,
        n_steps: usize,
        batch_size: usize,
    ) -> Result<Vec<f64>> {
        let n_vars = S::N_VARS;
        let n_params = S::N_PARAMS;

        if initial_states.len() != batch_size * n_vars {
            return Err(BarracudaError::InvalidInput {
                message: format!(
                    "initial_states: expected {} ([batch_size×{}]), got {}",
                    batch_size * n_vars,
                    n_vars,
                    initial_states.len()
                ),
            });
        }
        if params.len() != batch_size * n_params {
            return Err(BarracudaError::InvalidInput {
                message: format!(
                    "params: expected {} ([batch_size×{}]), got {}",
                    batch_size * n_params,
                    n_params,
                    params.len()
                ),
            });
        }

        let mut state: Vec<f64> = initial_states.to_vec();
        let mut t = 0.0_f64;

        for _step in 0..n_steps {
            for b in 0..batch_size {
                let s_off = b * n_vars;
                let p_off = b * n_params;
                let y: Vec<f64> = state[s_off..s_off + n_vars].to_vec();
                let p: Vec<f64> = params[p_off..p_off + n_params].to_vec();

                let k1 = S::cpu_derivative(t, &y, &p);
                let y2: Vec<f64> = y
                    .iter()
                    .zip(k1.iter())
                    .map(|(yi, k1i)| yi + 0.5 * dt * k1i)
                    .collect();
                let k2 = S::cpu_derivative(t + 0.5 * dt, &y2, &p);

                let y3: Vec<f64> = y
                    .iter()
                    .zip(k2.iter())
                    .map(|(yi, k2i)| yi + 0.5 * dt * k2i)
                    .collect();
                let k3 = S::cpu_derivative(t + 0.5 * dt, &y3, &p);

                let y4: Vec<f64> = y
                    .iter()
                    .zip(k3.iter())
                    .map(|(yi, k3i)| yi + dt * k3i)
                    .collect();
                let k4 = S::cpu_derivative(t + dt, &y4, &p);

                let sixth = 1.0 / 6.0;
                for i in 0..n_vars {
                    state[s_off + i] =
                        y[i] + dt * sixth * (k1[i] + 2.0 * k2[i] + 2.0 * k3[i] + k4[i]);
                }
            }
            t += dt;
        }

        Ok(state)
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    /// Exponential decay: dy/dt = -k*y, y(0)=y0 → y(t)=y0*exp(-k*t)
    struct ExponentialDecay;

    impl OdeSystem for ExponentialDecay {
        const N_VARS: usize = 1;
        const N_PARAMS: usize = 1;

        fn system_name() -> &'static str {
            "exponential_decay"
        }

        fn wgsl_derivative() -> &'static str {
            r#"
fn deriv(state: array<f64, 1>, params: array<f64, 1>, t: f64) -> array<f64, 1> {
    let k = params[0];
    var dy: array<f64, 1>;
    dy[0] = -k * state[0];
    return dy;
}
"#
        }

        fn wgsl_derivative_universal() -> Option<&'static str> {
            Some(
                r#"
fn deriv(state: array<Scalar, 1>, params: array<Scalar, 1>, t: Scalar) -> array<Scalar, 1> {
    let k = params[0];
    var dy: array<Scalar, 1>;
    dy[0] = op_neg(op_mul(k, state[0]));
    return dy;
}
"#,
            )
        }

        fn cpu_derivative(_t: f64, state: &[f64], params: &[f64]) -> Vec<f64> {
            let k = params[0];
            vec![-k * state[0]]
        }
    }

    #[test]
    fn test_exponential_decay_cpu_matches_analytical() {
        // dy/dt = -k*y, y(0)=1 → y(t)=exp(-k*t)
        let k = 1.0_f64;
        let t_final = 1.0_f64;
        let dt = 0.001_f64;
        let n_steps = (t_final / dt).round() as usize;

        let initial = vec![1.0];
        let params = vec![k];

        let result =
            BatchedOdeRK4::<ExponentialDecay>::integrate_cpu(&initial, &params, dt, n_steps, 1)
                .expect("integrate_cpu should succeed");

        let expected = (-k * t_final).exp();
        assert!(
            (result[0] - expected).abs() < 1e-6,
            "y(1) = {}, expected {}",
            result[0],
            expected
        );
    }

    #[test]
    fn test_exponential_decay_batched() {
        let initial = vec![1.0, 2.0]; // 2 batches
        let params = vec![1.0, 0.5]; // k=1 and k=0.5
        let dt = 0.01;
        let n_steps = 100;

        let result =
            BatchedOdeRK4::<ExponentialDecay>::integrate_cpu(&initial, &params, dt, n_steps, 2)
                .expect("integrate_cpu should succeed");

        let expected_0 = (-1.0_f64).exp();
        let expected_1 = 2.0 * (-0.5_f64).exp();
        assert!(
            (result[0] - expected_0).abs() < 1e-4,
            "batch 0: got {}, expected {}",
            result[0],
            expected_0
        );
        assert!(
            (result[1] - expected_1).abs() < 1e-4,
            "batch 1: got {}, expected {}",
            result[1],
            expected_1
        );
    }

    #[test]
    fn test_generated_wgsl_has_expected_structure() {
        let shader = BatchedOdeRK4::<ExponentialDecay>::generate_shader();
        assert!(shader.contains("fn main"));
        assert!(shader.contains("fn deriv"));
        assert!(shader.contains("fn rk4_step"));
        assert!(shader.contains("@compute @workgroup_size(64)"));
        assert!(shader.contains("const N_VARS:   u32 = 1u"));
        assert!(shader.contains("const N_PARAMS: u32 = 1u"));
    }

    #[test]
    fn test_generated_universal_wgsl_has_expected_structure() {
        let shader = BatchedOdeRK4::<ExponentialDecay>::generate_shader_universal()
            .expect("ExponentialDecay should have a universal derivative");
        assert!(shader.contains("fn main"));
        assert!(shader.contains("fn deriv"));
        assert!(shader.contains("fn rk4_step"));
        assert!(shader.contains("Scalar"));
        assert!(shader.contains("op_add"));
        assert!(shader.contains("op_mul"));
        assert!(shader.contains("op_from_f32"));
        assert!(
            !shader.contains("f64"),
            "universal template must not contain raw f64"
        );
    }

    #[test]
    fn test_generated_wgsl_compiles() {
        let Some(device) = crate::device::test_pool::get_test_device_if_f64_gpu_available_sync()
        else {
            return;
        };
        let shader = BatchedOdeRK4::<ExponentialDecay>::generate_shader();
        device.compile_shader_f64(&shader, Some("ode_generic_exponential_decay"));
    }

    #[test]
    fn test_integrate_cpu_invalid_initial_states_len() {
        let initial = vec![1.0, 2.0, 3.0]; // wrong size for batch_size=1
        let params = vec![1.0];
        let result =
            BatchedOdeRK4::<ExponentialDecay>::integrate_cpu(&initial, &params, 0.01, 10, 1);
        assert!(result.is_err());
    }

    #[test]
    fn test_integrate_cpu_invalid_params_len() {
        let initial = vec![1.0];
        let params = vec![1.0, 2.0]; // wrong size for batch_size=1
        let result =
            BatchedOdeRK4::<ExponentialDecay>::integrate_cpu(&initial, &params, 0.01, 10, 1);
        assert!(result.is_err());
    }
}
