#!/bin/bash
# Setup NVIDIA GPUs for sovereign BAR0 access (ecoPrimals compute)
#
# Run with: sudo ./scripts/setup-gpu-sovereign.sh
#
# This script:
# 1. Creates the gpu-mmio group (if needed)
# 2. Installs udev rules for BAR0 access
# 3. Optionally binds GPUs to VFIO for dual-use (gaming + science)
#
# Requirements:
# - NVIDIA GPU(s) with nouveau or nvidia driver
# - Root access (for udev rules and group creation)

set -e

RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
CYAN='\033[0;36m'
NC='\033[0m'

NVIDIA_VENDOR="10de"
RULES_FILE="/etc/udev/rules.d/99-ecoprimals-gpu-bar0.rules"
GROUP_NAME="gpu-mmio"

echo -e "${CYAN}=== ecoPrimals Sovereign GPU Setup ===${NC}"
echo ""

if [ "$EUID" -ne 0 ]; then
    echo -e "${RED}ERROR: Must run as root (sudo)${NC}"
    exit 1
fi

# 1. Detect NVIDIA GPUs
echo "1. Detecting NVIDIA GPUs..."
GPU_COUNT=0
for dev in /sys/bus/pci/devices/*; do
    if [ -f "$dev/vendor" ]; then
        vendor=$(cat "$dev/vendor" 2>/dev/null | tr -d '0x')
        if [ "$vendor" = "$NVIDIA_VENDOR" ]; then
            class=$(cat "$dev/class" 2>/dev/null)
            # 0x030000 = VGA, 0x030200 = 3D controller
            if [[ "$class" == 0x0302* ]] || [[ "$class" == 0x0300* ]]; then
                bdf=$(basename "$dev")
                driver="none"
                if [ -L "$dev/driver" ]; then
                    driver=$(readlink "$dev/driver" | xargs basename)
                fi
                device=$(cat "$dev/device" 2>/dev/null)
                echo -e "   ${GREEN}✓${NC} $bdf (device=$device, driver=$driver)"
                GPU_COUNT=$((GPU_COUNT + 1))
            fi
        fi
    fi
done

if [ $GPU_COUNT -eq 0 ]; then
    echo -e "   ${YELLOW}No NVIDIA GPUs found${NC}"
    exit 0
fi
echo "   Found $GPU_COUNT NVIDIA GPU(s)"

# 2. Create gpu-mmio group
echo ""
echo "2. Setting up $GROUP_NAME group..."
if getent group $GROUP_NAME > /dev/null 2>&1; then
    echo -e "   ${GREEN}✓${NC} Group $GROUP_NAME already exists"
else
    groupadd -f $GROUP_NAME
    echo -e "   ${GREEN}✓${NC} Created group $GROUP_NAME"
fi

CURRENT_USER=${SUDO_USER:-$USER}
if id -nG "$CURRENT_USER" | grep -qw "$GROUP_NAME"; then
    echo -e "   ${GREEN}✓${NC} User $CURRENT_USER already in $GROUP_NAME"
else
    usermod -aG $GROUP_NAME "$CURRENT_USER"
    echo -e "   ${GREEN}✓${NC} Added $CURRENT_USER to $GROUP_NAME"
    echo -e "   ${YELLOW}Note: Log out and back in for group change to take effect${NC}"
fi

# 3. Install udev rules for BAR0 access
echo ""
echo "3. Installing BAR0 udev rules..."
cat > "$RULES_FILE" << 'RULES'
# ecoPrimals sovereign GPU BAR0 access
# Auto-generated by setup-gpu-sovereign.sh
#
# Enables non-root MMIO register access for NVIDIA GPUs.
# Users must be in the 'gpu-mmio' group.

# NVIDIA vendor 0x10de — resource0 is BAR0 (MMIO registers)
SUBSYSTEM=="pci", ATTR{vendor}=="0x10de", \
  RUN+="/bin/chmod 0660 /sys/bus/pci/devices/%k/resource0"
SUBSYSTEM=="pci", ATTR{vendor}=="0x10de", \
  RUN+="/bin/chgrp gpu-mmio /sys/bus/pci/devices/%k/resource0"
RULES

echo -e "   ${GREEN}✓${NC} Wrote $RULES_FILE"

udevadm control --reload-rules
udevadm trigger
echo -e "   ${GREEN}✓${NC} udev rules reloaded"

# 4. Apply permissions immediately (don't wait for next boot)
echo ""
echo "4. Applying BAR0 permissions now..."
for dev in /sys/bus/pci/devices/*; do
    if [ -f "$dev/vendor" ]; then
        vendor=$(cat "$dev/vendor" 2>/dev/null | tr -d '0x')
        if [ "$vendor" = "$NVIDIA_VENDOR" ]; then
            class=$(cat "$dev/class" 2>/dev/null)
            if [[ "$class" == 0x0302* ]] || [[ "$class" == 0x0300* ]]; then
                bdf=$(basename "$dev")
                resource0="$dev/resource0"
                if [ -f "$resource0" ]; then
                    chmod 0660 "$resource0"
                    chgrp $GROUP_NAME "$resource0"
                    echo -e "   ${GREEN}✓${NC} $bdf/resource0 → mode 0660, group $GROUP_NAME"
                fi
            fi
        fi
    fi
done

# 5. Optional: VFIO setup
echo ""
echo "5. VFIO setup (optional — for dual-use gaming + science)..."
if [ -d "/sys/kernel/iommu_groups" ]; then
    GROUPS=$(ls /sys/kernel/iommu_groups 2>/dev/null | wc -l)
    echo -e "   ${GREEN}✓${NC} IOMMU enabled ($GROUPS groups)"
    echo -e "   ${CYAN}To bind a GPU to VFIO for sovereign compute:${NC}"
    echo "     echo <BDF> > /sys/bus/pci/devices/<BDF>/driver/unbind"
    echo "     echo $NVIDIA_VENDOR <DEVICE_ID> > /sys/bus/pci/drivers/vfio-pci/new_id"
    echo "     echo <BDF> > /sys/bus/pci/drivers/vfio-pci/bind"
else
    echo -e "   ${YELLOW}IOMMU not enabled — VFIO dual-use requires IOMMU${NC}"
    echo "   Add 'intel_iommu=on' or 'amd_iommu=on' to kernel cmdline"
fi

# Summary
echo ""
echo -e "${CYAN}=== Summary ===${NC}"
echo ""
echo "  GPUs found:      $GPU_COUNT"
echo "  udev rules:      $RULES_FILE"
echo "  Group:            $GROUP_NAME"
echo "  User:             $CURRENT_USER"
echo ""
echo "To test BAR0 access (after re-login for group):"
echo "  cargo run -p nvpmu --bin nvpmu-monitor"
echo ""
echo "To validate sovereign compute:"
echo "  cargo test -p nvpmu -- --ignored --test-threads=1"
