// SPDX-License-Identifier: AGPL-3.0-or-later
//! Manifest rendering and template helper functions
//!
//! Supports both TOML (preferred, ecoBin compliant) and YAML formats.

use crate::{CliContextExt, Result};
use tracing::info;

use super::types_mod::BiomeTemplate;
use crate::BiomeManifest;

pub fn get_template_tags(template: &BiomeTemplate) -> Vec<String> {
    match template {
        BiomeTemplate::Basic => vec!["basic".to_string(), "essential".to_string()],
        BiomeTemplate::Science => vec![
            "science".to_string(),
            "research".to_string(),
            "data-analysis".to_string(),
        ],
        BiomeTemplate::AiResearch => vec![
            "ai".to_string(),
            "ml".to_string(),
            "gpu".to_string(),
            "training".to_string(),
        ],
        BiomeTemplate::Quantum => vec![
            "quantum".to_string(),
            "simulation".to_string(),
            "research".to_string(),
        ],
        BiomeTemplate::Genomics => vec![
            "genomics".to_string(),
            "bioinformatics".to_string(),
            "secure".to_string(),
        ],
        BiomeTemplate::Vision => vec![
            "vision".to_string(),
            "imaging".to_string(),
            "opencv".to_string(),
            "gpu".to_string(),
        ],
        BiomeTemplate::Distributed => vec![
            "distributed".to_string(),
            "cluster".to_string(),
            "orchestration".to_string(),
        ],
        BiomeTemplate::Sovereign => vec![
            "sovereign".to_string(),
            "security".to_string(),
            "air-gapped".to_string(),
        ],
        BiomeTemplate::Development => vec![
            "development".to_string(),
            "testing".to_string(),
            "tools".to_string(),
        ],
        BiomeTemplate::Custom(_) => vec!["custom".to_string()],
    }
}

/// Convert manifest to TOML string (ecoBin compliant, preferred format)
///
/// TOML is the recommended format because:
/// - Pure Rust implementation (no C dependencies)
/// - Better for configuration files
/// - Native to Rust ecosystem
#[cfg(test)]
pub fn manifest_to_toml(manifest: &BiomeManifest) -> Result<String> {
    let mut toml_str = String::new();

    toml_str.push_str(&format!(
        "# {}\n",
        manifest
            .metadata
            .description
            .as_ref()
            .map_or("ToadStool Biome Manifest", String::as_str)
    ));
    toml_str.push_str("# Generated by ToadStool Universal Compute Platform\n");
    toml_str.push_str("# Format: TOML (ecoBin compliant)\n\n");

    let toml_content =
        toml::to_string_pretty(manifest).context("Failed to serialize manifest to TOML")?;

    toml_str.push_str(&toml_content);

    Ok(toml_str)
}

/// Convert manifest to YAML string (legacy format, backwards compatibility)
pub fn manifest_to_yaml(manifest: &BiomeManifest) -> Result<String> {
    let mut yaml = String::new();

    yaml.push_str(&format!(
        "# {}\n",
        manifest
            .metadata
            .description
            .as_ref()
            .map_or("ToadStool Biome Manifest", String::as_str)
    ));
    yaml.push_str("# Generated by ToadStool Universal Compute Platform\n");
    yaml.push_str("# Note: Consider migrating to TOML format for ecoBin compliance\n\n");

    let yaml_content =
        serde_yaml_ng::to_string(manifest).context("Failed to serialize manifest to YAML")?;

    yaml.push_str(&yaml_content);

    Ok(yaml)
}

/// Print informational message about generated template
pub fn print_template_info(template: &BiomeTemplate) {
    match template {
        BiomeTemplate::Basic => {
            info!("📦 Basic biome template generated");
            info!("   • Essential services for general computing");
            info!("   • PKI security service by default");
            info!("   • Resource limits: 4 CPU, 8GB RAM, 50GB storage");
        }
        BiomeTemplate::Science => {
            info!("🔬 Science biome template generated");
            info!("   • Jupyter notebook for interactive analysis");
            info!("   • PostgreSQL database for data storage");
            info!("   • Storage capability for research data");
            info!("   • Resource limits: 16 CPU, 32GB RAM, 500GB storage");
        }
        BiomeTemplate::AiResearch => {
            info!("🤖 AI Research biome template generated");
            info!("   • PyTorch and TensorFlow environments");
            info!("   • TensorBoard for experiment tracking");
            info!("   • GPU acceleration support");
            info!("   • Resource limits: 32 CPU, 128GB RAM, 2TB storage, 4 GPUs");
        }
        BiomeTemplate::Quantum => {
            info!("⚛️  Quantum Computing biome template generated");
            info!("   • Qiskit quantum development environment");
            info!("   • Quantum simulators and hardware access");
            info!("   • Resource limits: 64 CPU, 256GB RAM, 1TB storage");
        }
        BiomeTemplate::Genomics => {
            info!("🧬 Genomics biome template generated");
            info!("   • Bioinformatics pipeline tools");
            info!("   • Secure patient data handling");
            info!("   • Storage capability for datasets");
            info!("   • Resource limits: 32 CPU, 128GB RAM, 2TB storage");
        }
        BiomeTemplate::Vision => {
            info!("👁️  Computer Vision biome template generated");
            info!("   • OpenCV and imaging libraries");
            info!("   • GPU acceleration for processing");
            info!("   • Real-time video processing support");
            info!("   • Resource limits: 16 CPU, 64GB RAM, 1TB storage, 2 GPUs");
        }
        BiomeTemplate::Distributed => {
            info!("🌐 Distributed Computing biome template generated");
            info!("   • Multi-node cluster configuration");
            info!("   • Orchestration service");
            info!("   • Auto-scaling capabilities");
            info!("   • Resource limits: Scalable across nodes");
        }
        BiomeTemplate::Sovereign => {
            info!("🔒 Sovereign Computing biome template generated");
            info!("   • Maximum security configuration");
            info!("   • Air-gapped deployment support");
            info!("   • Hardware security module integration");
            info!("   • Resource limits: 8 CPU, 16GB RAM, 100GB storage");
        }
        BiomeTemplate::Development => {
            info!("🔧 Development biome template generated");
            info!("   • Development tools and testing environment");
            info!("   • Hot-reload capabilities");
            info!("   • Debug and profiling tools");
            info!("   • Resource limits: 8 CPU, 16GB RAM, 200GB storage");
        }
        BiomeTemplate::Custom(_) => {
            info!("⚙️  Custom biome template generated");
            info!("   • User-defined configuration");
            info!("   • Flexible resource allocation");
        }
    }

    info!("");
    info!("Next steps:");
    info!("  1. Review and customize the generated biome.yaml");
    info!("  2. Deploy with: toadstool biome deploy");
    info!("  3. Monitor with: toadstool biome status");
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_get_template_tags_basic() {
        let tags = get_template_tags(&BiomeTemplate::Basic);
        assert_eq!(tags, vec!["basic", "essential"]);
    }

    #[test]
    fn test_get_template_tags_science() {
        let tags = get_template_tags(&BiomeTemplate::Science);
        assert!(tags.contains(&"science".to_string()));
        assert!(tags.contains(&"research".to_string()));
    }

    #[test]
    fn test_get_template_tags_ai_research() {
        let tags = get_template_tags(&BiomeTemplate::AiResearch);
        assert!(tags.contains(&"ai".to_string()));
        assert!(tags.contains(&"gpu".to_string()));
    }

    #[test]
    fn test_get_template_tags_custom() {
        use super::super::types_mod::CustomTemplateSpec;
        let spec = CustomTemplateSpec {
            name: "my-tpl".to_string(),
            description: "test".to_string(),
            primals: vec![],
            services: vec![],
            security_level: "standard".to_string(),
            resource_profile: "minimal".to_string(),
        };
        let tags = get_template_tags(&BiomeTemplate::Custom(spec));
        assert_eq!(tags, vec!["custom"]);
    }

    #[test]
    fn test_get_template_tags_all_variants() {
        assert!(!get_template_tags(&BiomeTemplate::Quantum).is_empty());
        assert!(!get_template_tags(&BiomeTemplate::Genomics).is_empty());
        assert!(!get_template_tags(&BiomeTemplate::Vision).is_empty());
        assert!(!get_template_tags(&BiomeTemplate::Distributed).is_empty());
        assert!(!get_template_tags(&BiomeTemplate::Sovereign).is_empty());
        assert!(!get_template_tags(&BiomeTemplate::Development).is_empty());
    }

    #[test]
    fn test_get_template_tags_sovereign_has_security() {
        let tags = get_template_tags(&BiomeTemplate::Sovereign);
        assert!(tags.contains(&"sovereign".to_string()));
        assert!(tags.contains(&"security".to_string()));
    }

    #[test]
    fn test_get_template_tags_distributed_has_cluster() {
        let tags = get_template_tags(&BiomeTemplate::Distributed);
        assert!(tags.contains(&"cluster".to_string()));
        assert!(tags.contains(&"orchestration".to_string()));
    }

    #[test]
    fn test_manifest_to_toml() {
        use crate::{
            BiomeManifest, BiomeMetadata, BiomeNetworking, BiomeResources, BiomeSecurity,
            BiomeStorage,
        };
        use std::collections::HashMap;

        let now = std::time::SystemTime::now();
        let manifest = BiomeManifest {
            metadata: BiomeMetadata {
                name: "test-biome".to_string(),
                version: "1.0".to_string(),
                description: Some("Test manifest".to_string()),
                author: None,
                created: now,
                updated: now,
                tags: vec![],
            },
            primals: HashMap::new(),
            services: HashMap::new(),
            resources: BiomeResources {
                cpu_limit: Some(4.0),
                memory_limit: None,
                storage_limit: None,
                gpu_limit: None,
                network_bandwidth: None,
            },
            security: BiomeSecurity {
                isolation_level: "standard".to_string(),
                trust_level: "medium".to_string(),
                beardog_required: false,
                crypto_policies: vec![],
                allowed_networks: vec![],
                forbidden_syscalls: vec![],
            },
            networking: BiomeNetworking {
                mode: "bridge".to_string(),
                dns_servers: vec![],
                port_mappings: vec![],
                network_policies: vec![],
            },
            storage: BiomeStorage {
                nestgate_integration: None,
                datasets: vec![],
                volumes: vec![],
                backup_policy: None,
            },
        };

        let result = manifest_to_toml(&manifest);
        assert!(result.is_ok());
        let toml_str = result.unwrap();
        assert!(toml_str.contains("test-biome"));
        assert!(toml_str.contains("Test manifest"));
    }
}
