//! YAML rendering and template helper functions

use anyhow::{Context, Result};
use tracing::info;

use super::types_mod::BiomeTemplate;
use crate::BiomeManifest;

/// Get template tags for categorization
pub fn get_template_tags(template: &BiomeTemplate) -> Vec<String> {
    match template {
        BiomeTemplate::Basic => vec!["basic".to_string(), "essential".to_string()],
        BiomeTemplate::Science => vec![
            "science".to_string(),
            "research".to_string(),
            "data-analysis".to_string(),
        ],
        BiomeTemplate::AiResearch => vec![
            "ai".to_string(),
            "ml".to_string(),
            "gpu".to_string(),
            "training".to_string(),
        ],
        BiomeTemplate::Quantum => vec![
            "quantum".to_string(),
            "simulation".to_string(),
            "research".to_string(),
        ],
        BiomeTemplate::Genomics => vec![
            "genomics".to_string(),
            "bioinformatics".to_string(),
            "secure".to_string(),
        ],
        BiomeTemplate::Vision => vec![
            "vision".to_string(),
            "imaging".to_string(),
            "opencv".to_string(),
            "gpu".to_string(),
        ],
        BiomeTemplate::Distributed => vec![
            "distributed".to_string(),
            "cluster".to_string(),
            "songbird".to_string(),
        ],
        BiomeTemplate::Sovereign => vec![
            "sovereign".to_string(),
            "security".to_string(),
            "air-gapped".to_string(),
        ],
        BiomeTemplate::Development => vec![
            "development".to_string(),
            "testing".to_string(),
            "tools".to_string(),
        ],
        BiomeTemplate::Custom(_) => vec!["custom".to_string()],
    }
}

/// Convert manifest to YAML string
pub fn manifest_to_yaml(manifest: &BiomeManifest) -> Result<String> {
    let mut yaml = String::new();

    yaml.push_str(&format!(
        "# {}\n",
        manifest
            .metadata
            .description
            .as_ref()
            .unwrap_or(&"ToadStool Biome Manifest".to_string())
    ));
    yaml.push_str("# Generated by ToadStool Universal Compute Platform\n");
    yaml.push_str("# https://github.com/your-org/toadstool\n\n");

    let yaml_content =
        serde_yaml::to_string(manifest).context("Failed to serialize manifest to YAML")?;

    yaml.push_str(&yaml_content);

    Ok(yaml)
}

/// Print informational message about generated template
pub fn print_template_info(template: &BiomeTemplate) {
    match template {
        BiomeTemplate::Basic => {
            info!("📦 Basic biome template generated");
            info!("   • Essential services for general computing");
            info!("   • BearDog security by default");
            info!("   • Resource limits: 4 CPU, 8GB RAM, 50GB storage");
        }
        BiomeTemplate::Science => {
            info!("🔬 Science biome template generated");
            info!("   • Jupyter notebook for interactive analysis");
            info!("   • PostgreSQL database for data storage");
            info!("   • NestGate integration for research data");
            info!("   • Resource limits: 16 CPU, 32GB RAM, 500GB storage");
        }
        BiomeTemplate::AiResearch => {
            info!("🤖 AI Research biome template generated");
            info!("   • PyTorch and TensorFlow environments");
            info!("   • TensorBoard for experiment tracking");
            info!("   • GPU acceleration support");
            info!("   • Resource limits: 32 CPU, 128GB RAM, 2TB storage, 4 GPUs");
        }
        BiomeTemplate::Quantum => {
            info!("⚛️  Quantum Computing biome template generated");
            info!("   • Qiskit quantum development environment");
            info!("   • Quantum simulators and hardware access");
            info!("   • Resource limits: 64 CPU, 256GB RAM, 1TB storage");
        }
        BiomeTemplate::Genomics => {
            info!("🧬 Genomics biome template generated");
            info!("   • Bioinformatics pipeline tools");
            info!("   • Secure patient data handling");
            info!("   • NestGate integration for datasets");
            info!("   • Resource limits: 32 CPU, 128GB RAM, 2TB storage");
        }
        BiomeTemplate::Vision => {
            info!("👁️  Computer Vision biome template generated");
            info!("   • OpenCV and imaging libraries");
            info!("   • GPU acceleration for processing");
            info!("   • Real-time video processing support");
            info!("   • Resource limits: 16 CPU, 64GB RAM, 1TB storage, 2 GPUs");
        }
        BiomeTemplate::Distributed => {
            info!("🌐 Distributed Computing biome template generated");
            info!("   • Multi-node cluster configuration");
            info!("   • Songbird orchestration");
            info!("   • Auto-scaling capabilities");
            info!("   • Resource limits: Scalable across nodes");
        }
        BiomeTemplate::Sovereign => {
            info!("🔒 Sovereign Computing biome template generated");
            info!("   • Maximum security configuration");
            info!("   • Air-gapped deployment support");
            info!("   • Hardware security module integration");
            info!("   • Resource limits: 8 CPU, 16GB RAM, 100GB storage");
        }
        BiomeTemplate::Development => {
            info!("🔧 Development biome template generated");
            info!("   • Development tools and testing environment");
            info!("   • Hot-reload capabilities");
            info!("   • Debug and profiling tools");
            info!("   • Resource limits: 8 CPU, 16GB RAM, 200GB storage");
        }
        BiomeTemplate::Custom(_) => {
            info!("⚙️  Custom biome template generated");
            info!("   • User-defined configuration");
            info!("   • Flexible resource allocation");
        }
    }

    info!("");
    info!("Next steps:");
    info!("  1. Review and customize the generated biome.yaml");
    info!("  2. Deploy with: toadstool biome deploy");
    info!("  3. Monitor with: toadstool biome status");
}
