//! Pure RPC Types for ToadStool Server
//!
//! **CONSOLIDATED**: Re-exports from `toadstool_integration_protocols::tarpc_service`
//! to eliminate duplication and ensure single source of truth.
//!
//! ## Evolution Path
//!
//! 1. **Before**: Duplicate definitions in both protocols crate and server crate
//! 2. **Problem**: Duplication led to inconsistencies (e.g., `health_check` vs `health_status`)
//! 3. **Solution**: Consolidate to single source in `tarpc_service.rs` with semantic method naming
//! 4. **Current**: Re-export from protocols crate (single source of truth)

use serde::{Deserialize, Serialize};
use std::collections::HashMap;

// Re-export all RPC types from the primary definition
// Note: ToadStoolComputeRpcClient is generated by tarpc macro and available from tarpc_service module
pub use toadstool_integration_protocols::tarpc_service::{
    AvailableResources, ComputeCapabilities, ComputeUnit, ExecutionMetrics, HealthStatus,
    ResourceRequirements, ToadStoolComputeRpc, WorkloadPriority, WorkloadResult, WorkloadStatus,
    WorkloadSubmission,
};

// Re-export client type (generated by tarpc macro)
pub use toadstool_integration_protocols::tarpc_service::ToadStoolComputeRpcClient;

// Re-export semantic method mapping utilities
pub use toadstool_integration_protocols::tarpc_service::semantic_methods;

/// Tarpc-specific workload submission (with serialized data)
///
/// This is a server-specific type that extends WorkloadSubmission
/// for tarpc-specific serialization needs.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct TarpcWorkloadSubmission {
    /// Workload identifier
    pub workload_id: String,
    /// Runtime type
    pub runtime_type: String,
    /// Serialized workload data
    pub payload: Vec<u8>,
    /// Resource requirements
    pub resources: ResourceRequirements,
    /// Metadata
    pub metadata: HashMap<String, String>,
}
